### PR TITLE
A pull request

### PR DESCRIPTION
**Pull request by Ochuwa-sophie**

### CODE REVIEW

**Comment by stewartmcgown** [comment]
Thanks! Make sure you check over the syntax for JS objects. You cannot declare a value inside an object definition.

**Comment by Ochuwa-sophie** [comment]
Noted.
I'll edit it ASAP.

**Comment by stewartmcgown** [comment]
For example, this is the error you get when attempting to put an identifier in an object definition:

image

**Comment by Ochuwa-sophie** [comment]
Found this after 3 years....

**Pull request closed without merging**
